### ISSUE TITLE
redshift

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#26]

**Comment by emk** [comment]
This is going to wait until several other non-trivial things are done first:

1. I finish porting to a newer nightly (going well). I have no interest in writing new code against old versions of anything for this particular project. :-/
2. I add S3 "CSVs in buckets" support. Not hard, I don't think.

**Comment by seamusabshere** [comment]
ok

**Comment by emk** [comment]
Further investigation reveals that RedShift is sufficiently compatible with PostgreSQL that it supports off-the-shelf `psql`. So there's at least _some_ chance that `\copy` works correctly. If this is true, we can just use `postgres:` URLs with `dbcrossbar` for preliminary support.

**Comment by emk** [comment]
Try running "copy to" using a `postgres:` URL as well, if you haven't already. It _might_ work. :-)

**Comment by emk** [comment]
So, it's unclear exactly how compatible RedShift is with `psql`. Online docs are mixed. I did find the docs for bulk loading and unloading via S3, however:

- https://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html
- https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html

The nice part about this is that it's a bulk interface. There may be downsides, too.

**Comment by emk** [comment]
Notably, it looks like `COPY` may not support PostgreSQL binary format, which may make it harder to load some of the more complicated data types (because we already know that CSV loads have limitations, especially regarding arrays).

On the positive side, `COPY` will apparently accept input in Avro format, which is basically a binary CSV-like format.

- [RedShift Avro notes](https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-format.html#copy-avro)
- [`avro` crate for Rust](https://docs.rs/avro-rs/)
- [Apache Avro spec](https://avro.apache.org/docs/current/spec.html)

The Rust Avro crate looks promising, so it probably shouldn't be too hard to read or write Avro format. And Avro is one of the better-supported formats for BigQuery. So it's worth keeping this in mind as a fallback.

**Comment by emk** [comment]
Ready for review at #48.
