### ISSUE TITLE
Error: unknown user-defined data type "citext"

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/dbcrossbar#81]
let's say mytable has a `citext` column

```
$  dbcrossbar conv $POSTGRES_URL?sslmode=require#mytable postgres-sql:mytable.sql
Error: unknown user-defined data type "citext"
```

should just be treated as text

**Comment by emk** [comment]
Thank you for the bug report!

The easiest way to get support for weird PostgreSQL types is to provide a "work in progress" PR which updates just these two files:

- https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbar/fixtures/more_pg_types.sql (add a column with the new copy)
- https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbar/fixtures/more_pg_types.csv (add the same column with a sample value, which must be in the format produced by `\copy example_table to stdout`)

Then I'll then check out the PR and make the test cases pass again.

We do it this way because there are often weird special cases in how things should be declared and handled, and providing a test case with actual data has prevented a number of time-consuming "Oh, that's not what I meant" cycles in the past. Thank you!

**Comment by emk** [comment]
Thank you for your bug report! We'd be happy to add support for more PostgreSQL column types.

However, we've found that these feature requests tend to suffer from an unusually high level of miscommunication. So we have a small request to make, to make sure we get this right the first time. Could you please provide us with some test data?

Here's how you can do that.

Let's say you want to add a type `character(2)`. You'll need to have a copy of PostgreSQL running, and you'll need access to a scratch database.

```
postgres=# create table example (c character(2));
CREATE TABLE
postgres=# insert into example values ('ab');
INSERT 0 1
postgres=# \copy example to stdout csv header
c
ab
```
...except replace `character(2)` with the column type you want to support, and change the `insert` command to insert a value of the correct type. When you're done, please paste the output of the above commands here.

We'll use this information to update the test cases in:

- [dbcrossbar/fixtures/more_pg_types.sql](https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbar/fixtures/more_pg_types.sql)
- [dbcrossbar/fixtures/more_pg_types.csv](https://github.com/faradayio/dbcrossbar/blob/master/dbcrossbar/fixtures/more_pg_types.csv)

...and then we'll update our PostgreSQL drivers to make the test case pass.

Thank you very much for your feature request!

**Comment by emk** [comment]
Oh, weird, that's technically an extension type, not a built-in one.

This will be fixed in the next release.
