### ISSUE TITLE
cp fails on bigquery to postgres for column names with capital letters

### ISSUE THREAD

**Issue by markberger** [faradayio/dbcrossbar#84]
I got this error on mac with release `v0.2.8`.

I have a table in bigquery where columns have capital letters, such as `Col_Name`. When I ran `./dbcrossbar cp --temporary=gs:/my-bucket/ bigquery:bq-project:dataset.table 'postgres://postgres:@localhost:5432/db#table'` I encountered the following error:

`Error: CSV file has column col_name at position 1, but schema has Col_Name`

It looks like dbcrossbar selects the columns in BigQuery via the lowercase names. This causes the csv files to have a lowercase header, which does not match up with the schema generated by dbcrossbar for postgres.

**Comment by emk** [comment]
Thank you for the bug report! Sorry for the slow reply; we've been busy with an internal project deadline and the holidays.

Uppercase column names are currently problematic, mostly because BigQuery column names are actually more restrictive than the (old?) BigQuery documentation claimed. I'm happy to add a test case and fix this particular problem. But if you would like to have the smoothest possible experience moving data between databases, then I would suggest using all lowercase column names and limiting the characters to valid C identifiers.

`dbcrossbar` is basically a never-ending battle against weird corner cases, and I'm happy to handle as many as possible. But given the complexity of the problem, we tend to discover these issues the hard way, rather than being able to eliminate them all up front. So please keep the bug reports coming!
